[project]
name="bashlib toml"		# Name of the project
author="Jachin Minyard"		# Author of the project
tool="toml"			# name of the tool script
include="bashlib_toml"		# name of the include library file.
repo=""				# The projects repo

[dirs]
bin="bin"
lib="lib"
libexec="libexec"
man="man"
